"""initial migration

Revision ID: 09696678a93e
Revises: 
Create Date: 2023-02-08 10:26:58.348372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09696678a93e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('affiliation', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_affiliation'), 'persons', ['affiliation'], unique=False)
    op.create_index(op.f('ix_persons_id'), 'persons', ['id'], unique=False)
    op.create_index(op.f('ix_persons_name'), 'persons', ['name'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state', sa.Enum('Wait', 'Play', 'End', name='roomstateenum'), nullable=True),
    sa.Column('time_offset', sa.Integer(), nullable=True),
    sa.Column('time_duration', sa.Integer(), nullable=True),
    sa.Column('init_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_table('games',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('win', sa.Integer(), nullable=True),
    sa.Column('draw', sa.Integer(), nullable=True),
    sa.Column('lose', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('room_id', 'person_id')
    )
    op.create_table('hands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hand', sa.Enum('Rock', 'Scissor', 'Paper', name='handenum'), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id', 'person_id'], ['games.room_id', 'games.person_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hands_id'), 'hands', ['id'], unique=False)
    op.create_index(op.f('ix_hands_person_id'), 'hands', ['person_id'], unique=False)
    op.create_index(op.f('ix_hands_room_id'), 'hands', ['room_id'], unique=False)
    op.create_index(op.f('ix_hands_time'), 'hands', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hands_time'), table_name='hands')
    op.drop_index(op.f('ix_hands_room_id'), table_name='hands')
    op.drop_index(op.f('ix_hands_person_id'), table_name='hands')
    op.drop_index(op.f('ix_hands_id'), table_name='hands')
    op.drop_table('hands')
    op.drop_table('games')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_persons_name'), table_name='persons')
    op.drop_index(op.f('ix_persons_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_affiliation'), table_name='persons')
    op.drop_table('persons')
    # ### end Alembic commands ###
