"""empty message

Revision ID: 31d3e6f0f0c6
Revises: 
Create Date: 2022-12-13 18:23:52.358364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d3e6f0f0c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_games_draw', table_name='games')
    op.drop_index('ix_games_lose', table_name='games')
    op.drop_index('ix_games_person_id', table_name='games')
    op.drop_index('ix_games_rank', table_name='games')
    op.drop_index('ix_games_room_id', table_name='games')
    op.drop_index('ix_games_score', table_name='games')
    op.drop_index('ix_games_win', table_name='games')
    op.drop_column('games', 'id')
    op.drop_index('ix_hands_time', table_name='hands')
    op.drop_constraint(None, 'hands', type_='foreignkey')
    op.drop_constraint(None, 'hands', type_='foreignkey')
    op.drop_constraint(None, 'hands', type_='foreignkey')
    op.create_foreign_key(None, 'hands', 'games', ['room_id', 'person_id'], ['room_id', 'person_id'])
    op.drop_column('hands', 'game_id')
    op.drop_index('ix_persons_affiliation', table_name='persons')
    op.drop_index('ix_persons_name', table_name='persons')
    op.drop_index('ix_rooms_state', table_name='rooms')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_rooms_state', 'rooms', ['state'], unique=False)
    op.create_index('ix_persons_name', 'persons', ['name'], unique=False)
    op.create_index('ix_persons_affiliation', 'persons', ['affiliation'], unique=False)
    op.add_column('hands', sa.Column('game_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'hands', type_='foreignkey')
    op.create_foreign_key(None, 'hands', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key(None, 'hands', 'persons', ['person_id'], ['id'])
    op.create_foreign_key(None, 'hands', 'games', ['game_id'], ['id'])
    op.create_index('ix_hands_time', 'hands', ['time'], unique=False)
    op.add_column('games', sa.Column('id', sa.INTEGER(), nullable=True))
    op.create_index('ix_games_win', 'games', ['win'], unique=False)
    op.create_index('ix_games_score', 'games', ['score'], unique=False)
    op.create_index('ix_games_room_id', 'games', ['room_id'], unique=False)
    op.create_index('ix_games_rank', 'games', ['rank'], unique=False)
    op.create_index('ix_games_person_id', 'games', ['person_id'], unique=False)
    op.create_index('ix_games_lose', 'games', ['lose'], unique=False)
    op.create_index('ix_games_draw', 'games', ['draw'], unique=False)
    # ### end Alembic commands ###
