export const Language = [
  {
    title: "RPS Brawl",
    intro_text: "Enjoy Rock Scissor Paper with several friends! 😁",
    rule: "Rule",
    explanation: `The lastest hand is shown in the center of the screen.
          If you win the hand, you will get +1 points. But if not, you will get -1 points. `,
    start: "Start",
    entrance: "Start",
    name: "name",
    join: "Join",
    quit: "Quit",
    places: "Places",
    play: "play",
    network_logs: "Network logs",
    rooms: "Rooms",
    create_room: "Create Room",
    quick_start: "Quick Start",
    mode: "Mode",
    normal: "Normal",
    limited: "Limited",
    privateRoom: "Private room",
    create: "Create",
    cancel: "Cancel",
    update: "Update",
    settings: "Settings",

    ingame_title_text: "Thinking about which hand to play...",
    ingame_describe_text: (num) => {
      return `The game starts soon ( connected : ${num} ) `;
    },
    team: "Team",
    add_bot: "Add bots",
    skilled: "Skilled",
    dumb: "Dumb",
    teams: ["red", "orange", "yellow", "green", "blue", "navy", "purple"],
    time_over: "time over",
    save_result: "Save result",
    result_page_text: (count) => {
      return `You'll be moved to the room in ${count} seconds...`;
    },
    no_room_text: "Create new room to play!😁",
  },
  {
    title: "RPS Brawl",
    intro_text: "여러명의 친구들과 가위바위보 난투를 즐기세요! 😁",
    rule: "규칙",
    explanation: `가장 마지막에 낸 사람의 손이 화면에 크게 보입니다. 이 손을 이기면
          +1점! 지면 -1점! 60초 안에 가장 많은 점수를 획득하세요!`,
    start: "시작",
    entrance: "입장",
    name: "이름",
    join: "참여",
    quit: "나가기",
    play: "시작",
    places: "순위",
    network_logs: "네트워크 로그",
    rooms: "방목록",
    create_room: "방 만들기",
    quick_start: "빠른 시작",
    mode: "모드",
    normal: "일반",
    limited: "한 손 제한",
    privateRoom: "비밀방",
    create: "생성",
    cancel: "취소",
    update: "변경",
    settings: "설정",
    limited_explain_text: " ",

    ingame_title_text: "무엇을 낼지 고민하는 중..",
    ingame_describe_text: (num) => {
      return `난투가 곧 시작됩니다. ( 현재 : ${num}명 ) `;
    },
    team: "팀",
    add_bot: "봇 추가",
    skilled: "실력봇",
    dumb: "트롤봇",
    teams: ["빨강", "오렌지", "노랑", "초록", "파랑", "네이비", "보라"],
    time_over: "시간 종료",
    save_result: "결과 저장",
    result_page_text: (count) => {
      return `${count} 초 후에 대기실로 이동됩니다...`;
    },
    no_room_text: "방을 생성하고 게임을 즐기세요!😁",
  },
];
